#setup_travis

lane :build_for_testing do
  cocoapods
  scan(
    clean: true,
    devices: ["iPhone 11"]
  )
end

lane :run_tests do 
  scan(
    clean: false,
    devices: ["iPhone 11"]
  )
end  

lane :build_and_test do 
  build_for_testing
  run_tests
  add_badge
end
