setup_travis
app_name = "Tinkoff Chat"
repo_url = "https://github.com/IamMarik/TinkoffChat/"
author_name = "Marat Dzhanybaev"
icon_url = "https://acdn.tinkoff.ru/static/documents/80f3f5f9-eabc-4b45-9c5f-30c048a8a756.png"
last_commit_hash = ""
last_build_and_test_result = "New commit successfully builded and tested."

desc "Build app without running tests"
lane :build_for_testing do
  cocoapods
  scan(
    build_for_testing: true,
    devices: ["iPhone 11"]
  )
end

desc "Run tests without building"
lane :run_tests do 
  scan(
    clean: false,
    skip_build: true,
    devices: ["iPhone 11"]
  )
end  

desc "Build app, run tests and report to discord channel"
lane :build_and_test do
  last_commit_hash = last_git_commit[:commit_hash]
  build_for_testing
  run_tests
  discord_report
rescue => ex
  last_build_and_test_result = "Commit failed build and tests."
  discord_report
end

desc "Send report message to discord channel"
lane :discord_report do
  webhook_url = ENV['DISCORD_WEBHOOK_URL']
  secret_token = ENV['DISCORD_TOKEN']
  client_url = webhook_url + secret_token
  client = Discordrb::Webhooks::Client.new(url: client_url)
  client.execute do |builder|
    builder.add_embed do |embed|
      embed.title = app_name
      embed.colour = 0x3c9b00
      embed.url = repo_url + "commit/" + last_commit_hash
      embed.description = last_build_and_test_result
      embed.author = Discordrb::Webhooks::EmbedAuthor.new(
        name: author_name, 
        url: repo_url, 
        icon_url: icon_url)
      embed.timestamp = Time.now
    end
  end
end
